USE `test_db`;

CREATE TABLE `untraceable` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `lea_id` bigint(20) DEFAULT NULL,
  `phone` varchar(255) COLLATE utf8_spanish_ci DEFAULT NULL,
  `sou_id` bigint(20) DEFAULT NULL,
  `ddi` varchar(255) COLLATE utf8_spanish_ci DEFAULT NULL,
  `sms_date` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_Untraceable_deleted_at` (`deleted_at`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci


CREATE SCHEMA `crmti`;
USE `crmti`;

CREATE TABLE `lea_leads` (
  `lea_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `lea_ts` timestamp NOT NULL DEFAULT current_timestamp(),
  `lea_type` int(11) unsigned NOT NULL DEFAULT 0,
  `lea_source` int(11) unsigned NOT NULL DEFAULT 0,
  `lea_lot` int(11) unsigned NOT NULL DEFAULT 1,
  `lea_assigned` int(11) unsigned DEFAULT NULL,
  `lea_scheduled` datetime DEFAULT NULL,
  `lea_scheduled_auto` int(1) DEFAULT 0,
  `lea_cost` float(6,4) unsigned NOT NULL DEFAULT 0.0000,
  `lea_seen` int(11) NOT NULL DEFAULT 0,
  `lea_closed` int(1) NOT NULL DEFAULT 0,
  `lea_new` int(1) unsigned NOT NULL DEFAULT 1,
  `lea_client` int(1) NOT NULL DEFAULT 0,
  `lea_date_control` date NOT NULL,
  `TELEFONO` varchar(255) COLLATE utf8_spanish_ci DEFAULT '',
  `nombre` varchar(100) COLLATE utf8_spanish_ci DEFAULT '',
  `apellido1` varchar(30) COLLATE utf8_spanish_ci DEFAULT '',
  `apellido2` varchar(30) COLLATE utf8_spanish_ci DEFAULT '',
  `dninie` varchar(23) COLLATE utf8_spanish_ci DEFAULT '',
  `observaciones` text COLLATE utf8_spanish_ci DEFAULT NULL,
  `hashid` varchar(255) COLLATE utf8_spanish_ci DEFAULT '',
  `nombrecompleto` varchar(255) COLLATE utf8_spanish_ci DEFAULT '',
  `movil` varchar(9) COLLATE utf8_spanish_ci DEFAULT '',
  `url` varchar(500) COLLATE utf8_spanish_ci DEFAULT '',
  `asnef` varchar(64) COLLATE utf8_spanish_ci DEFAULT '',
  `wsid` int(11) DEFAULT NULL,
  `ip` varchar(50) COLLATE utf8_spanish_ci DEFAULT '',
  `Email` varchar(128) COLLATE utf8_spanish_ci DEFAULT '',
  `tipocliente` varchar(255) COLLATE utf8_spanish_ci DEFAULT '',
  `escliente` varchar(64) COLLATE utf8_spanish_ci DEFAULT '',
  `tiposolicitud` varchar(64) COLLATE utf8_spanish_ci DEFAULT '',
  `fechasolicitud` date DEFAULT NULL,
  `poblacion` varchar(90) COLLATE utf8_spanish_ci DEFAULT '',
  `provincia` varchar(255) COLLATE utf8_spanish_ci DEFAULT '',
  `direccion` varchar(400) COLLATE utf8_spanish_ci DEFAULT '',
  `observaciones2` text COLLATE utf8_spanish_ci DEFAULT NULL,
  `contacto2` varchar(255) COLLATE utf8_spanish_ci DEFAULT '',
  `cargo` varchar(255) COLLATE utf8_spanish_ci DEFAULT '',
  `cantidaddeseada` varchar(11) COLLATE utf8_spanish_ci DEFAULT '',
  `cantidadofrecida` varchar(11) COLLATE utf8_spanish_ci DEFAULT '',
  `ncliente` varchar(255) COLLATE utf8_spanish_ci DEFAULT '',
  `calle` varchar(30) COLLATE utf8_spanish_ci DEFAULT '',
  `cp` varchar(8) COLLATE utf8_spanish_ci DEFAULT '',
  `interesadoen` varchar(64) COLLATE utf8_spanish_ci DEFAULT '',
  `numero` varchar(10) COLLATE utf8_spanish_ci DEFAULT '',
  `1` varchar(255) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'Deleted',
  `compaiaactualfibraadsl` varchar(30) COLLATE utf8_spanish_ci DEFAULT '',
  `companiaactualmovil` varchar(30) COLLATE utf8_spanish_ci DEFAULT '',
  `fibraactual` varchar(255) COLLATE utf8_spanish_ci DEFAULT '',
  `moviactuallineaprincipal` varchar(64) COLLATE utf8_spanish_ci DEFAULT '',
  `numerolineasadicionales` int(2) DEFAULT NULL,
  `tarifaactualsiniva` float DEFAULT 0,
  `motivocambio` varchar(64) COLLATE utf8_spanish_ci DEFAULT '',
  `importeaumentado` int(11) DEFAULT NULL COMMENT 'Deleted',
  `importeretirado` int(11) DEFAULT NULL COMMENT 'Deleted',
  `tipoordenador` varchar(64) COLLATE utf8_spanish_ci DEFAULT '',
  `sector` varchar(64) COLLATE utf8_spanish_ci DEFAULT '',
  `presupuesto` varchar(64) COLLATE utf8_spanish_ci DEFAULT '',
  `rendimiento` varchar(64) COLLATE utf8_spanish_ci DEFAULT '',
  `movilidad` varchar(64) COLLATE utf8_spanish_ci DEFAULT '',
  `tipouso` varchar(64) COLLATE utf8_spanish_ci DEFAULT '',
  `Office365` varchar(64) COLLATE utf8_spanish_ci DEFAULT '',
  PRIMARY KEY (`lea_id`,`lea_date_control`),
  KEY `lea_type` (`lea_type`) USING BTREE,
  KEY `lea_source` (`lea_source`) USING BTREE,
  KEY `lea_lot` (`lea_lot`) USING BTREE,
  KEY `lea_scheduled` (`lea_scheduled`) USING BTREE,
  KEY `lea_assigned` (`lea_assigned`) USING BTREE,
  KEY `lea_new` (`lea_new`) USING BTREE,
  KEY `TELEFONO` (`TELEFONO`),
  KEY `movil` (`movil`),
  KEY `dninie` (`dninie`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci

insert into crmti.lea_leads (sub_id, sub_action) values (341, '{"result":"2-cierre","cierreTipo":"1-positivo"}');