apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: untraceable-cronjob
  namespace: josedelrio85-pre
spec:
  schedule: "12 07 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: untraceable
            image: 952729869933.dkr.ecr.eu-west-1.amazonaws.com/untraceable:latest
            env:
            - name: DB_HOST
              value: "leads-pre.c848y92oajny.eu-west-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "leads"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: leads-database
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: leads-database
                  key: pass
            - name: LLEIDANET_ENDPOINT
              value: https://api.lleida.net/sms/v2/
            - name: LLEIDANET_USER
              valueFrom:
                secretKeyRef:
                  name: lleidanet
                  key: user
            - name: LLEIDANET_PASS
              valueFrom:
                secretKeyRef:
                  name: lleidanet
                  key: pass
            - name: LLEIDANET_ALARM_PHONE
              value: "6356852582"
          restartPolicy: Never